version: "3.1"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_node
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: express_node
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    ports:
      - 8081:8081